// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar/>
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   );
// }




import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/providers';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
// import Navbar from '../components/Navbar';
// import Footer from '../components/Footer';
// import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nuha - Pure Nature, Pure Goodness',
  description: 'Your trusted source for premium organic and natural products. Shop fresh organic food, natural beauty products, supplements, and eco-friendly home goods.',
  keywords: 'organic, natural products, healthy living, eco-friendly, sustainable',
  authors: [{ name: 'Nuha' }],
  openGraph: {
    title: 'Nuha - Pure Nature, Pure Goodness',
    description: 'Your trusted source for premium organic and natural products',
    type: 'website',
    locale: 'en_US',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Navbar/>
            <main className="flex-grow">
              {children}
            </main>
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  );
}